name: flutter_to_do_list
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.5.0
  msh_checkbox: ^2.0.1 
  uuid: ^4.3.3
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/

